behaviors:
    default:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512 
            buffer_size: 51200
            learning_rate_schedule: linear
            learning_rate: 1e-1
        network_settings:
            hidden_units: 512
            normalize: false
            num_layers: 4
            vis_encode_type: simple
            memory:
                memory_size: 512
                sequence_length: 512
        max_steps: 10.0e5
        time_horizon: 64    
        summary_freq: 10000
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
    PathFollowing:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512
            buffer_size: 51200
            learning_rate_schedule: linear
            learning_rate: 1e-5
        network_settings:
            hidden_units: 512
            num_layers: 6
            vis_encode_type: simple
        max_steps: 50.0e6
        time_horizon: 128
        summary_freq: 10000
        
torch_settings:
    device: cuda
    
env_settings:
    num_envs: 6